### ISSUE TITLE
Error on extension loading

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [xiyaowong/coc-sumneko-lua#11]
This happens on version 0.0.12. When Installing and opening a lua file:
```
[coc.nvim]: UnhandledRejection: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at Socket.Writable.write (node:internal/streams/writable:335:10)
    at /home/jtcf/.vim/plugged/coc.nvim/build/index.js:35:3107
    at new Promise (<anonymous>)
    at xF.write (/home/jtcf/.vim/plugged/coc.nvim/build/index.js:35:3028)
```
```
[coc.nvim]: UnhandledRejection: Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:371:5)
    at _write (node:internal/streams/writable:322:11)
    at Socket.Writable.write (node:internal/streams/writable:335:10)
    at /home/jtcf/.vim/plugged/coc.nvim/build/index.js:35:3107
    at new Promise (<anonymous>)
    at xF.write (/home/jtcf/.vim/plugged/coc.nvim/build/index.js:35:3028)
    at GS.doWrite (/home/jtcf/.vim/plugged/coc.nvim/build/index.js:36:1698)
    at /home/jtcf/.vim/plugged/coc.nvim/build/index.js:36:1597
```
After this "Initializing sumneko-lua" appears on status bar, but it never initializes.

**Comment by JohnTheCoolingFan** [comment]
Issue resolved by itself
