### ISSUE TITLE
[coc.nvim] Restarting server failed

### ISSUE THREAD

**Issue by gennaro-tedesco** [xiyaowong/coc-sumneko-lua#32]
Since the release [v3.5.6](https://github.com/sumneko/vscode-lua/releases/tag/v3.5.6) of `vscode-lua` I get the following errors opening any lua file:
```
[coc.nvim] Restarting server failed
```
followed by
```
[coc.nvim] Pending response rejected since connection got disposed
```
The language server does not work after such error messages, neither the completions nor the go-to-definition and such. Do you happen to have an idea about what can cause such failures? The message is quite obscure, but all other `CoC` plugins work as expected (so it _is_ about `coc-sumneko-lua` after all).

On further inspection, by using `:CocOpenLog` I see the following log message for the exception:
```
2022-09-21T01:58:58.127 INFO (pid:12856) [services] - registered service "sumneko-lua"
2022-09-21T01:58:58.130 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.130 INFO (pid:12856) [plugin] - coc.nvim initialized with node: v18.9.0 after 142ms
2022-09-21T01:58:58.140 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12865
2022-09-21T01:58:58.167 ERROR (pid:12856) [language-client] - Sending request failed.
2022-09-21T01:58:58.168 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.168 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.169 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.170 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.170 ERROR (pid:12856) [extensions-manager] - Error on active extension coc-sumneko-lua: Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.170 ERROR (pid:12856) [extensions-manager] - Error on activate coc-sumneko-lua Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.171 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:58:58.173 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12866
2022-09-21T01:58:58.178 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.179 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.179 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.179 ERROR (pid:12856) [services] - Server sumneko-lua failed to start: Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.180 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:58:58.181 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12868
2022-09-21T01:58:58.186 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:58:58.187 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.187 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:58:58.188 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:58:58.189 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12869
2022-09-21T01:58:58.194 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:58:58.195 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:01.591 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:01.749 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:01.838 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:01.957 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:02.355 INFO (pid:12856) [attach] - receive notification: openList [ 'commands' ]
2022-09-21T01:59:14.438 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.596 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.675 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.764 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:14.989 INFO (pid:12856) [attach] - Request action: listNames []
2022-09-21T01:59:15.491 INFO (pid:12856) [attach] - receive notification: openList [ 'commands' ]
2022-09-21T01:59:22.814 INFO (pid:12856) [services] - registered service "sumneko-lua"
2022-09-21T01:59:22.814 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.816 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12876
2022-09-21T01:59:22.821 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.821 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.821 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.821 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.822 ERROR (pid:12856) [list-session] - Error on action run Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.822 ERROR (pid:12856) [node-client] - Pending response rejected since connection got disposed Error: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
2022-09-21T01:59:22.822 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:22.824 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12877
2022-09-21T01:59:22.828 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.829 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.829 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.829 ERROR (pid:12856) [services] - Server sumneko-lua failed to start: Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.829 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:22.831 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12878
2022-09-21T01:59:22.836 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: stopped => starting
2022-09-21T01:59:22.836 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.836 INFO (pid:12856) [services] - LanguageClient Sumneko Lua Language Server state change: starting => stopped
2022-09-21T01:59:22.837 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:22.838 INFO (pid:12856) [language-client-index] - Language server "sumneko-lua" started with 12879
2022-09-21T01:59:22.844 ERROR (pid:12856) [language-client-client] - Server sumneko-lua initialization failed. Gm [Error]: Pending response rejected since connection got disposed
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:50:4562)
    at Object.dispose (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:215:89956)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10821)
    at gf.handleConnectionClosed (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:224:3604)
    at t (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:220:10473)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230)
    at Re (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:24:6501)
    at KA.invoke (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:14460)
    at Xd.fire (/Users/gennaro/.config/nvim/plugged/coc.nvim/build/index.js:23:15230) {
  code: -32097,
  data: undefined
}
2022-09-21T01:59:22.845 ERROR (pid:12856) [server] - unhandledRejection  Promise { <rejected> undefined } undefined
2022-09-21T01:59:28.547 INFO (pid:12856) [attach] - receive notification: openLog []
```

**Comment by Congee** [comment]
I have the same error and sumneko-lua logged some interesting error, especially this line

> [23:47:00.467][warn] [#0:script/proto/proto.lua:104]: Response of [workspace/configuration] error [-32603]: Request workspace/configuration failed with message: library.includes is not a function

Does anyone have any idea about this line or error? I've used the latest coc-sumneko-lua coc.nvim (release branch)

```
[23:46:59.745][info] [#0:/nix/store/iy0pzlwnrsx46a4nafr58sibi52w604s-sumneko-lua-language-server-3.5.6/share/lua-language-server/main.lua:65]: Lua Lsp startup, root: 	/nix/store/iy0pzlwnrsx46a4nafr58sibi52w604s-sumneko-lua-language-server-3.5.6/share/lua-language-server
[23:46:59.745][info] [#0:/nix/store/iy0pzlwnrsx46a4nafr58sibi52w604s-sumneko-lua-language-server-3.5.6/share/lua-language-server/main.lua:66]: ROOT:	/nix/store/iy0pzlwnrsx46a4nafr58sibi52w604s-sumneko-lua-language-server-3.5.6/share/lua-language-server
[23:46:59.745][info] [#0:/nix/store/iy0pzlwnrsx46a4nafr58sibi52w604s-sumneko-lua-language-server-3.5.6/share/lua-language-server/main.lua:67]: LOGPATH:	/tmp/sumneko-lua
[23:46:59.745][info] [#0:/nix/store/iy0pzlwnrsx46a4nafr58sibi52w604s-sumneko-lua-language-server-3.5.6/share/lua-language-server/main.lua:68]: METAPATH:	/home/congee/.cache/sumneko_lua/meta
[23:46:59.745][info] [#0:/nix/store/iy0pzlwnrsx46a4nafr58sibi52w604s-sumneko-lua-language-server-3.5.6/share/lua-language-server/main.lua:69]: VERSION:	3.5.6
[23:46:59.762][info] [#0:script/service/service.lua:141]: 
========= Medical Examination Report =========
    --------------- Memory ---------------
        Total: 1.410 MB
        # 00 : 1.410 MB
        # 01 : 0.000 MB
        # 02 : 0.000 MB
        # 03 : 0.000 MB
        # 04 : 0.000 MB
    --------------- Coroutine ---------------
        Total:     0
        Running:   0
        Suspended: 0
        Normal:    0
        Dead:      0
    --------------- Cache ---------------
        Total: 1
        Dead:  0
    ---------------  RPC  ---------------
        Holdon:   0
        Waiting:  0
==============================================
[23:46:59.765][info] [#0:script/language.lua:137]: VSC language: en-us
[23:46:59.765][info] [#0:script/language.lua:138]: LS  language: en-us
[23:46:59.765][info] [#0:script/workspace/workspace.lua:38]: Workspace init root: 	file:///home/congee/nix
[23:46:59.765][info] [#0:script/workspace/workspace.lua:42]: Log path: 	/tmp/sumneko-lua/file_home_congee_nix.log
[23:46:59.765][info] [#0:script/workspace/workspace.lua:51]: Workspace create: 	file:///home/congee/nix
[23:47:00.467][warn] [#0:script/proto/proto.lua:104]: Response of [workspace/configuration] error [-32603]: Request workspace/configuration failed with message: library.includes is not a function
[23:47:00.467][warn] [#0:script/config/loader.lua:116]: No config?	nil
[23:47:00.467][info] [#0:script/provider/completion.lua:43]: Enable completion.
[23:47:00.567][warn] [#0:script/proto/proto.lua:104]: Response of [workspace/configuration] error [-32603]: Request workspace/configuration failed with message: library.includes is not a function
[23:47:00.567][warn] [#0:script/config/loader.lua:116]: No config?	nil
[23:47:00.567][info] [#0:script/provider/provider.lua:56]: Load config from client	fallback
[23:47:00.567][info] [#0:script/provider/provider.lua:57]: nil
[23:47:00.668][info] [#0:script/library.lua:207]: Init builtin library at:	file:///home/congee/nix
[23:47:00.674][info] [#0:script/plugin.lua:86]: plugin path:	/home/congee/nix
[23:47:00.674][warn] [#0:script/plugin.lua:101]: plugin not found:	/home/congee/nix
[23:47:00.674][info] [#0:script/library.lua:207]: Init builtin library at:	nil
[23:47:00.679][info] [#0:script/workspace/workspace.lua:305]: Preload start:	file:///home/congee/nix
[23:47:00.680][info] [#0:script/workspace/workspace.lua:311]: Scan files at:	file:///home/congee/nix
[23:47:00.680][info] [#0:script/workspace/workspace.lua:305]: Preload start:	<fallback>
[23:47:00.680][info] [#0:script/workspace/workspace.lua:328]: Scan library at:	file:///home/congee/.cache/sumneko_lua/meta/Lua%205.4%20en-us%20utf8
[23:47:00.815][info] [#0:script/workspace/workspace.lua:328]: Scan library at:	file:///home/congee/.cache/sumneko_lua/meta/Lua%205.4%20en-us%20utf8
[23:47:00.815][info] [#0:script/workspace/workspace.lua:348]: Found 11 files at:	<fallback>
[23:47:00.815][info] [#0:script/workspace/loading.lua:153]: Load files from disk:	<fallback>
[23:47:00.815][info] [#0:script/workspace/workspace.lua:348]: Found 15 files at:	file:///home/congee/nix
[23:47:00.816][info] [#0:script/workspace/loading.lua:153]: Load files from disk:	file:///home/congee/nix
[23:47:02.764][info] [#0:script/workspace/loading.lua:165]: Loaded files takes [0.036] sec: <fallback>
[23:47:02.764][info] [#0:script/workspace/loading.lua:174]: Compile files takes [0.000] sec: <fallback>
[23:47:02.764][info] [#0:script/workspace/loading.lua:175]: Loaded finish:	<fallback>
[23:47:02.765][info] [#0:script/workspace/workspace.lua:350]: Preload finish at:	<fallback>
[23:47:02.766][info] [#0:script/workspace/loading.lua:165]: Loaded files takes [0.038] sec: file:///home/congee/nix
[23:47:02.766][info] [#0:script/workspace/loading.lua:174]: Compile files takes [0.000] sec: file:///home/congee/nix
[23:47:02.766][info] [#0:script/workspace/loading.lua:175]: Loaded finish:	file:///home/congee/nix
[23:47:02.766][info] [#0:script/workspace/workspace.lua:350]: Preload finish at:	file:///home/congee/nix
[23:47:02.779][warn] [#0:script/proto/proto.lua:122]: Response of [workspace/diagnostic/refresh] error [-32601]: Unhandled method workspace/diagnostic/refresh
[23:47:02.779][warn] [#0:script/proto/proto.lua:122]: Response of [workspace/diagnostic/refresh] error [-32601]: Unhandled method workspace/diagnostic/refresh
[23:47:04.765][info] [#0:script/provider/diagnostic.lua:486]: Diagnostics scope [<fallback>], files count:[15]
[23:47:04.765][info] [#0:script/provider/diagnostic.lua:486]: Diagnostics scope [file:///home/congee/nix], files count:[15]
[23:47:04.862][info] [#0:script/provider/diagnostic.lua:503]: Diagnostics scope [<fallback>] finished, takes [0.098] sec.
[23:47:04.862][info] [#0:script/provider/diagnostic.lua:503]: Diagnostics scope [file:///home/congee/nix] finished, takes [0.098] sec.
```
