### ISSUE TITLE
Completion doesn't work

### ISSUE THREAD

**Issue by chrisniael** [xiyaowong/coc-sumneko-lua#36]
- Windows 10
- NeoVim 0.8.3
- coc.nvim 0.0.82-b7375d5f
- coc-sumneko-lua 0.0.37

Completion doesn't work after using it for a while.

![image](https://user-images.githubusercontent.com/5593254/222032252-01babed1-f617-42af-a654-8429eaac5f01.png)

Expected:

![image](https://user-images.githubusercontent.com/5593254/222032185-4d3ef105-108a-4a7f-a428-c34f4b446e0d.png)

Here is coc.vim's error log

```
2023-03-01T10:40:20.531 ERROR (pid:22844) [completion-complete] - Complete error: sumneko-lua jh [Error]
    at C:\Users\IGG\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:51:3652
    at new Promise (<anonymous>)
    at Object.sendRequest (C:\Users\IGG\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:51:3401)
    at Object.sendRequest (C:\Users\IGG\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:241:5768)
    at Nd.sendRequest (C:\Users\IGG\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:244:1921)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:446:9)
    at async Am.doComplete (C:\Users\IGG\AppData\Local\nvim-data\plugged\coc.nvim\build\index.js:257:6457) {
  code: -32603,
  data: undefined
}
```

Here is [sumneko/vscode-lua](https://github.com/sumneko/vscode-lua)'s error log

```
[16:04:31.377][error][#0:script\core\completion\auto-require.lua:61]: script\core\completion\auto-require.lua:61: attempt to index a nil value
stack traceback:
        script\core\completion\auto-require.lua:61: in function 'core.completion.auto-require.check'
        script\core\completion\completion.lua:407: in upvalue 'checkModule'
        script\core\completion\completion.lua:1457: in upvalue 'tryWord'
        script\core\completion\completion.lua:2231: in upvalue 'tryCompletions'
        script\core\completion\completion.lua:2247: in function 'core.completion.completion.completion'
        script\provider\provider.lua:622: in function <script\provider\provider.lua:597>
        [C]: in function 'xpcall'
        script\proto\proto.lua:191: in function <script\proto\proto.lua:166>
```

**Comment by xiyaowong** [comment]
之前我好像也遇到过这个问题，当时忘记给官方提pr，刚测试了一下，应该已经修复了
