### ISSUE TITLE
Language server fails to start on systems with incompatible glibc

### ISSUE THREAD

**Issue by gorjusborg** [xiyaowong/coc-sumneko-lua#6]
The `lua-language-server` binary downloaded upon initialization doesn't work on versions of linux that have a different glibc version. 

## steps to reproduce

* rm -rf ~/.config/coc/extensions/coc-sumneko-lua-data # if present
* nvim +'CocInstall coc-sumneko-lua'
* open file.lua
* use option 1 to install language server

## Error message
```
[coc.nvim]: UnhandledRejection: write EPIPE
Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:798:11)
    at Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at /home/user/.config/nvim/plugged/coc.nvim/build/index.js:35:3107
    at new Promise (<anonymous>)
    at DF.write (/home/user/.config/nvim/plugged/coc.nvim/build/index.js:35:3028)
    at QS.doWrite (/home/user/.config/nvim/plugged/coc.nvim/build/index.js:36:1698)
```

Unfortunately, coc.nvim doesn't provide good feedback when the language server fails, so it took a while to figure out what was wrong. It becomes clear when running the executable directly. 

```
$ cd  ~/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/Linux
$ ./lua-language-server 
./lua-language-server: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.27' not found (required by ./lua-language-server)
./lua-language-server: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./lua-language-server)
```

## Workaround

For people encountering this issue, you can simply replace the `lua-language-server` executable with one you've compiled against the locally available glibc. 

```
$ git clone git@github.com:sumneko/lua-language-server.git #follow build instructions
$ cd 3rd/luamake && ./compile/install.sh && cd ../..  && ./3rd/luamake/luamake rebuild && cp bin/Linux/lua-language-server ~/.config/coc/extensions/coc-sumneko-lua-data/sumneko-lua-ls/extension/server/bin/Linux/
```

It seems like this project is assuming every linux system has the same libraries.

**Comment by carlocab** [comment]
> I will provide an option to set the binary path.

Can we still have this option? There are no builds of `lua-language-server` for macOS ARM64, but you can install one using Homebrew or MacPorts, so it would be convenient to be able to be able to use those here.
